---
title: "640finalproj"
author: "Gaojia Xu, Guanqi Zeng"
date: '2022-04-21'
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyr)
library(dplyr)
library(caret)
```

```{r}
data_ori <- read_sav('STAR_Students.sav')
#filter dataset, keep var we use
data <- data_ori %>% 
  select(gender, race, gkfreelunch, gkschid, gktmathss, gkclasstype) %>%
  filter(gkclasstype %in% c(1, 2)) %>%
  #because 244764 school only has treatment data
  filter(gkschid != 244764) %>%
  #filter(race != 6) %>%
  drop_na() 
  
  
 
#data wrangling
data <- data %>%
  mutate(gender=as.factor(ifelse(gender==2,1,0)), 
         race = as.factor(ifelse(race==2,1,0)),
         gkfreelunch = as.factor(ifelse(gkfreelunch==2, 0, 1)),
         gkschid = as.factor(gkschid),
         gkclasstype = as.factor(ifelse(gkclasstype==2,0,1)),
         gktmathss = gktmathss / sd(gktmathss[gkclasstype==0]))
```

```{r}
#get index for control/trt group
data_control_idx <- which(data$gkclasstype==0)
data_control <- data %>% filter(gkclasstype==0)
data_trt_idx <- which(data$gkclasstype==1)
data_trt <- data %>% filter(gkclasstype==1)
```

```{r}
#1. calculate normal unadjusted ATE and adjusted ATE
tau_unadjust <- mean(data$gktmathss[data_trt_idx])-mean(data$gktmathss[data_control_idx])
fit1 <- lm(gktmathss ~ ., data=data)
tau_adjust <- fit1$coefficients[['gkclasstype1']]
```

```{r}
#2. endogenous generate 3 groups
fit_tauk <- lm(gktmathss ~ gender+race+gkfreelunch+gkschid, data=data_control)
fit_tauk_pred <- predict(fit_tauk, data)

tauk_low_idx <- which(fit_tauk_pred <= quantile(fit_tauk_pred, 1/3))
tauk_high_idx <- which(fit_tauk_pred > quantile(fit_tauk_pred, 2/3))
tauk_medium_idx <- which(fit_tauk_pred > quantile(fit_tauk_pred, 1/3) & fit_tauk_pred <= quantile(fit_tauk_pred, 2/3))
```

```{r}
#calculate endogenous unadjusted ATE 

## low
tauk_unadjust_low_trt <- data$gktmathss[intersect(tauk_low_idx, data_trt_idx)]
tauk_unadjust_low_control <- data$gktmathss[intersect(tauk_low_idx, data_control_idx)]
tauk_unadjust_low <- mean(tauk_unadjust_low_trt)-mean(tauk_unadjust_low_control)

## medium
tauk_unadjust_medium_trt <- data$gktmathss[intersect(tauk_medium_idx, data_trt_idx)]
tauk_unadjust_medium_control <- data$gktmathss[intersect(tauk_medium_idx, data_control_idx)]
tauk_unadjust_medium <- mean(tauk_unadjust_medium_trt)-mean(tauk_unadjust_medium_control)

## high
tauk_unadjust_high_trt <- data$gktmathss[intersect(tauk_high_idx, data_trt_idx)]
tauk_unadjust_high_control <- data$gktmathss[intersect(tauk_high_idx, data_control_idx)]
tauk_unadjust_high <- mean(tauk_unadjust_high_trt)-mean(tauk_unadjust_high_control)
```

```{r}
# calculate endogenous adjusted ATE

## low
fit_tauk_low <- lm(gktmathss ~ ., data=data[tauk_low_idx,])
tauk_adjust_low <- fit_tauk_low$coefficients[['gkclasstype1']]

## medium
fit_tauk_medium <- lm(gktmathss ~ ., data=data[tauk_medium_idx,])
tauk_adjust_medium <- fit_tauk_medium$coefficients[['gkclasstype1']]

## high
fit_tauk_high <- lm(gktmathss ~ ., data=data[tauk_high_idx,])
tauk_adjust_high <- fit_tauk_high$coefficients[['gkclasstype1']]
```

```{r}
#3. endogenous LOO generate 3 groups
fit_tauk_loo_control_pred <- c()
for (i in 1:nrow(data_control)){
  fit_tauk_loo <- lm(gktmathss ~ gender+race+gkfreelunch+gkschid, data=data_control[-i,])
  fit_tauk_loo_pred <- predict(fit_tauk_loo, newdata=data_control[i,])
  fit_tauk_loo_control_pred <- c(fit_tauk_loo_control_pred, fit_tauk_loo_pred)
}

```

```{r}
# grouping for LOO
## create new dataset copy from tauk prediction, replace control group predicted value with new LOO predicted value, keep treatment group predicted value unchanged
loo_tau_pred <- fit_tauk_pred
loo_tau_pred[data_control_idx] <- fit_tauk_loo_control_pred

## low
tauk_loo_low_idx <- which(loo_tau_pred <= quantile(loo_tau_pred,1/3))

## high
tauk_loo_high_idx <- which(loo_tau_pred > quantile(loo_tau_pred,2/3))

## medium
tauk_loo_medium_idx <- which((loo_tau_pred > quantile(loo_tau_pred,1/3)) & (loo_tau_pred <= quantile(loo_tau_pred,2/3)))
```

```{r}
#calculate endogenous unadjusted ATE LOO

## low
tauk_loo_unadjust_low_trt <- data$gktmathss[intersect(tauk_loo_low_idx, data_trt_idx)]
tauk_loo_unadjust_low_control <- data$gktmathss[intersect(tauk_loo_low_idx, data_control_idx)]
tauk_loo_unadjust_low <- mean(tauk_loo_unadjust_low_trt)-mean(tauk_loo_unadjust_low_control)

## medium
tauk_loo_unadjust_medium_trt <- data$gktmathss[intersect(tauk_loo_medium_idx, data_trt_idx)]
tauk_loo_unadjust_medium_control <- data$gktmathss[intersect(tauk_loo_medium_idx, data_control_idx)]
tauk_loo_unadjust_medium <- mean(tauk_loo_unadjust_medium_trt)-mean(tauk_loo_unadjust_medium_control)

## high
tauk_loo_unadjust_high_trt <- data$gktmathss[intersect(tauk_loo_high_idx, data_trt_idx)]
tauk_loo_unadjust_high_control <- data$gktmathss[intersect(tauk_loo_high_idx, data_control_idx)]
tauk_loo_unadjust_high <- mean(tauk_loo_unadjust_high_trt)-mean(tauk_loo_unadjust_high_control)
```

```{r}
# calculate endogenous LOO adjusted ATE

## low
fit_tauk_loo_low <- lm(gktmathss ~ ., data=data[tauk_loo_low_idx,])
tauk_loo_adjust_low <- fit_tauk_loo_low$coefficients[['gkclasstype1']]

## medium
fit_tauk_loo_medium <- lm(gktmathss ~ ., data=data[tauk_loo_medium_idx,])
tauk_loo_adjust_medium <- fit_tauk_loo_medium$coefficients[['gkclasstype1']]

## high
fit_tauk_loo_high <- lm(gktmathss ~ ., data=data[tauk_loo_high_idx,])
tauk_loo_adjust_high <- fit_tauk_loo_high$coefficients[['gkclasstype1']]
```

```{r}
#4. endogenous splitted sample(ESS)
tauk_ess_unadjust_low_curr <- c()
tauk_ess_unadjust_medium_curr <- c()
tauk_ess_unadjust_high_curr <- c()

tauk_ess_adjust_low_curr <- c()
tauk_ess_adjust_medium_curr <- c()
tauk_ess_adjust_high_curr <- c()


for (i in c(1:100)){
  # randomly assign to grediction group or estimatino group in control data
  data_control_predgrp_idx <- sample(data_control_idx, nrow(data_control)/2)
  data_control_predgrp <- data[data_control_predgrp_idx,]
  data_control_estgrp_idx <- setdiff(data_control_idx, data_control_predgrp_idx)
  data_control_estgrp <- data[data_control_estgrp_idx,]
  
  fit_tauk_ess <- lm(gktmathss ~ gender+race+gkfreelunch+gkschid, data=data_control_predgrp)
  fit_tauk_ess_pred <- predict(fit_tauk_ess, newdata=data)
  
  # seperate to 3 groups
  tauk_ess_low_idx <- which(fit_tauk_ess_pred <= quantile(fit_tauk_ess_pred,1/3))
  tauk_ess_high_idx <- which(fit_tauk_ess_pred > quantile(fit_tauk_ess_pred,2/3))
  tauk_ess_medium_idx <- which((fit_tauk_ess_pred > quantile(fit_tauk_ess_pred,1/3)) & (fit_tauk_ess_pred <= quantile(fit_tauk_ess_pred,2/3)))
  
  # endogenous ESS unadjusted ATE
  ## low
  tauk_ess_unadjust_low_trt <- data$gktmathss[intersect(tauk_ess_low_idx, data_trt_idx)]
  tauk_ess_unadjust_low_control <- data$gktmathss[intersect(tauk_ess_low_idx, data_control_estgrp_idx)]
  tauk_ess_unadjust_low <- mean(tauk_ess_unadjust_low_trt)-mean(tauk_ess_unadjust_low_control)
  tauk_ess_unadjust_low_curr <- c(tauk_ess_unadjust_low_curr, tauk_ess_unadjust_low)
  
  ## medium
  tauk_ess_unadjust_medium_trt <- data$gktmathss[intersect(tauk_ess_medium_idx, data_trt_idx)]
  tauk_ess_unadjust_medium_control <- data$gktmathss[intersect(tauk_ess_medium_idx, data_control_estgrp_idx)]
  tauk_ess_unadjust_medium <- mean(tauk_ess_unadjust_medium_trt)-mean(tauk_ess_unadjust_medium_control)
  tauk_ess_unadjust_medium_curr <- c(tauk_ess_unadjust_medium_curr, tauk_ess_unadjust_medium)
  
  ## high
  tauk_ess_unadjust_high_trt <- data$gktmathss[intersect(tauk_ess_high_idx, data_trt_idx)]
  tauk_ess_unadjust_high_control <- data$gktmathss[intersect(tauk_ess_high_idx, data_control_estgrp_idx)]
  tauk_ess_unadjust_high <- mean(tauk_ess_unadjust_high_trt)-mean(tauk_ess_unadjust_high_control)
  tauk_ess_unadjust_high_curr <- c(tauk_ess_unadjust_high_curr, tauk_ess_unadjust_high)
  
  # endogenous ESS adjusted ATE
  ## low
  fit_tauk_ess_low <- lm(gktmathss ~ ., data=data[tauk_ess_low_idx,])
  tauk_ess_adjust_low <- fit_tauk_ess_low$coefficients[['gkclasstype1']]
  tauk_ess_adjust_low_curr <- c(tauk_ess_adjust_low_curr, tauk_ess_adjust_low)
  
  ## medium
  fit_tauk_ess_medium <- lm(gktmathss ~ ., data=data[tauk_ess_medium_idx,])
  tauk_ess_adjust_medium <- fit_tauk_ess_medium$coefficients[['gkclasstype1']]
  tauk_ess_adjust_medium_curr <- c(tauk_ess_adjust_medium_curr, tauk_ess_adjust_medium)
  
  ## high
  fit_tauk_ess_high <- lm(gktmathss ~ ., data=data[tauk_ess_high_idx,])
  tauk_ess_adjust_high <- fit_tauk_ess_high$coefficients[['gkclasstype1']]
  tauk_ess_adjust_high_curr <- c(tauk_ess_adjust_high_curr, tauk_ess_adjust_high)
}
```

```{r}
tauk_ess_unadjust_low_mean <- mean(tauk_ess_unadjust_low_curr)
tauk_ess_unadjust_medium_mean <- mean(tauk_ess_unadjust_medium_curr)
tauk_ess_unadjust_high_mean <- mean(tauk_ess_unadjust_high_curr)

tauk_ess_adjust_low_mean <- mean(tauk_ess_adjust_low_curr)
tauk_ess_adjust_medium_mean <- mean(tauk_ess_adjust_medium_curr)
tauk_ess_adjust_high_mean <- mean(tauk_ess_adjust_high_curr)
```


```{r}
#5. endogenous 10-fold leave out
fit_tauk_10fold_control_pred <- c()
flds <- createFolds(data_control_idx, k = 10, list = FALSE, returnTrain = FALSE)
## create new dataset copy from tauk prediction
fold_tau_pred <- fit_tauk_pred

for (i in 1:10){
  fit_tauk_10fold <- lm(gktmathss ~ gender+race+gkfreelunch+gkschid, data=data_control[-which(flds == i),])
  fit_tauk_10fold_pred <- predict(fit_tauk_10fold, newdata=data_control[which(flds == i),])
  #replace control group predicted value with new 10fold leave out predicted value, keep treatment group predicted value unchanged
  fold_tau_pred[data_control_idx][which(flds == i)] <- fit_tauk_10fold_pred
}
```

```{r}
# grouping for 10fold leave out
## low
tauk_10fold_low_idx <- which(fold_tau_pred <= quantile(fold_tau_pred,1/3))
## high
tauk_10fold_high_idx <- which(fold_tau_pred > quantile(fold_tau_pred,2/3))
## medium
tauk_10fold_medium_idx <- which((fold_tau_pred > quantile(fold_tau_pred,1/3)) & (fold_tau_pred <= quantile(fold_tau_pred,2/3)))
```

```{r}
#calculate endogenous unadjusted ATE ten-fold Leave out
## low
tauk_10fold_unadjust_low_trt <- data$gktmathss[intersect(tauk_10fold_low_idx, data_trt_idx)]
tauk_10fold_unadjust_low_control <- data$gktmathss[intersect(tauk_10fold_low_idx, data_control_idx)]
tauk_10fold_unadjust_low <- mean(tauk_10fold_unadjust_low_trt)-mean(tauk_10fold_unadjust_low_control)

## medium
tauk_10fold_unadjust_medium_trt <- data$gktmathss[intersect(tauk_10fold_medium_idx, data_trt_idx)]
tauk_10fold_unadjust_medium_control <- data$gktmathss[intersect(tauk_10fold_medium_idx, data_control_idx)]
tauk_10fold_unadjust_medium <- mean(tauk_10fold_unadjust_medium_trt)-mean(tauk_10fold_unadjust_medium_control)

## high
tauk_10fold_unadjust_high_trt <- data$gktmathss[intersect(tauk_10fold_high_idx, data_trt_idx)]
tauk_10fold_unadjust_high_control <- data$gktmathss[intersect(tauk_10fold_high_idx, data_control_idx)]
tauk_10fold_unadjust_high <- mean(tauk_10fold_unadjust_high_trt)-mean(tauk_10fold_unadjust_high_control)
```

```{r}
# calculate endogenous 10fold leave out adjusted ATE
## low
fit_tauk_10fold_low <- lm(gktmathss ~ ., data=data[tauk_10fold_low_idx,])
tauk_10fold_adjust_low <- fit_tauk_10fold_low$coefficients[['gkclasstype1']]

## medium
fit_tauk_10fold_medium <- lm(gktmathss ~ ., data=data[tauk_10fold_medium_idx,])
tauk_10fold_adjust_medium <- fit_tauk_10fold_medium$coefficients[['gkclasstype1']]

## high
fit_tauk_10fold_high <- lm(gktmathss ~ ., data=data[tauk_10fold_high_idx,])
tauk_10fold_adjust_high <- fit_tauk_10fold_high$coefficients[['gkclasstype1']]
```











