---
title: "Simulation2"
author: "Gaojia Xu"
date: '2022-04-23'
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(pracma)
library(caret)
library(proxyC)
library(ggplot2)
library(ggpubr)
```


```{r, eval=FALSE}
# function: yhatf.m
## predicted outcome of the whole dataset based on the model use only control group
yhatf <- function(data = star){
  Y0 <- data%>%filter(V2==0)%>%select(V1)
  N0 <- nrow(Y0)
  X0 <- as.matrix(cbind(rep(1, N0), data%>%filter(V2==0)%>%select(-c(V1,V2))))
  
  beta <- as.matrix(pinv(t(X0) %*% X0) %*% t(X0) %*% as.matrix(Y0))
  pred_outcome <- as.matrix(cbind(rep(1, nrow(data)), data%>%select(-c(V1,V2)))) %*% beta
  return(pred_outcome)
}

## use to simplify the first loop in former LOO design(meant to reduce overfitting--use LOO samples to predict Y of the leaved sample)
## can replace the control group predicted Y at one time

yhatfl <- function(data = star){
  Y0 <- as.matrix(data%>%filter(V2==0)%>%select(V1))
  N0 <- nrow(Y0)
  X0 <- as.matrix(cbind(rep(1, N0), data%>%filter(V2==0)%>%select(-c(V1,V2))))
  
  beta <- as.matrix(pinv(t(X0) %*% X0) %*% t(X0) %*% Y0)
  pred_outcome <- as.matrix(cbind(rep(1, nrow(data)), data%>%select(-c(V1,V2)))) %*% beta
  
  e0 <- Y0 - X0 %*% beta

  Q <- pinv(t(X0) %*% X0)
  h <- diag(X0 %*% Q %*% t(X0))
  
  sp_mat <- diag(as.vector(e0/(1-h)), nrow = N0, ncol = N0)
    
  predicted_outcome_cross_validated <- pred_outcome
  predicted_outcome_cross_validated[which(data$V2==0)] <- X0 %*% beta - diag(X0 %*% Q %*% t(X0) %*% sp_mat)
  return(predicted_outcome_cross_validated)
}
```


```{r, eval=FALSE}
# function: mregbygroup.m
mregbygroup <- function(data = star, pred_outcome){
  n <- nrow(data)
  
  # individuals in treatment & control 
  data_trt_idx <- which(data$V2==1)
  data_control_idx <- which(data$V2==0)
  
  # unadjusted 
  ## low
  tau1_idx <- which(pred_outcome <= quantile(pred_outcome,1/3))
  tau1_trt <- data$V1[intersect(tau1_idx, data_trt_idx)]
  tau1_control <- data$V1[intersect(tau1_idx, data_control_idx)]
  tau1_unadj <- mean(tau1_trt)-mean(tau1_control)
  
  ## medium
  tau2_idx <- which((pred_outcome > quantile(pred_outcome,1/3)) & (pred_outcome <= quantile(pred_outcome,2/3)))
  tau2_trt <- data$V1[intersect(tau2_idx, data_trt_idx)]
  tau2_control <- data$V1[intersect(tau2_idx, data_control_idx)]
  tau2_unadj <- mean(tau2_trt)-mean(tau2_control)
  
  ## high
  tau3_idx <- which(pred_outcome > quantile(pred_outcome,2/3))
  tau3_trt <- data$V1[intersect(tau3_idx, data_trt_idx)]
  tau3_control <- data$V1[intersect(tau3_idx, data_control_idx)]
  tau3_unadj <- mean(tau3_trt)-mean(tau3_control)
  
  # adjusted
  ## low
  fit_tau1 <- lm(V1 ~ ., data=data[tau1_idx,])
  tau1_adjust <- fit_tau1$coefficients[['V2']]
  
  ## medium
  fit_tau2 <- lm(V1 ~ ., data=data[tau2_idx,])
  tau2_adjust <- fit_tau2$coefficients[['V2']]
  
  ## high
  fit_tau3 <- lm(V1 ~ ., data=data[tau3_idx,])
  tau3_adjust <- fit_tau3$coefficients[['V2']]
  
  return(c(tau1_unadj, tau2_unadj, tau3_unadj, tau1_adjust, tau2_adjust, tau3_adjust))
}
```

```{r, eval=FALSE}
# hyperparameters
K <- c(10,20,40)
N <- c(200,1000,5000)
R <- 100
M <- 100
SSR <- 100
ps <- 1/2

lK <- length(K)
lN <- length(N)

results <- list()
```

```{r warning = F, eval=FALSE}
for(i_k in 1:lK){
  k <- K[i_k]
  beta <- rep(1, k+1)
  
  for(i_n in 1:lN){
    n <- N[i_n]
    V2 <- c(rep(0,n/2), rep(1, n/2))
    
    est = matrix(0,nrow = R, ncol = 6)
    estl = matrix(0,nrow = R, ncol = 6)
    estss = matrix(0,nrow = R, ncol = 6)
    estf = matrix(0,nrow = R, ncol = 6)
    
    for(r in 1:R){
      print(c(k,n,r))
      x <- cbind(rep(1, n), matrix(rnorm(n*k), nrow = n, ncol = k))
      z <- matrix(rnorm(n * (M-k)), nrow = n, ncol = M-k)
      
      y <- cbind(x,z) %*% rep(1, M+1)
      V1 <- y
      
      x <- as.data.frame(cbind(V1, V2, x))
      
      # get predicted outcome
      yhat <- yhatf(data = x)
      yhatl <- yhatfl(data = x)
      
      # record results
      tauk <- mregbygroup(data = x, pred_outcome = yhat)
      taukl <- mregbygroup(data = x, pred_outcome = yhatl)
      
      
      # generate tau for ss
      x_control_idx <- which(x$V2==0)
      x_control <- x[x_control_idx,]
  
      resultss <- matrix(0, nrow = SSR, ncol = 6)
      for (i in c(1:SSR)){
      # randomly assign to prediction group or estimation group in control data
        predgrp_idx <- sample(x_control_idx, size = nrow(x_control)/2)
        predgrp <- x[predgrp_idx,]
        estgrp_idx <- setdiff(x_control_idx, predgrp_idx)
        estgrp <- x[estgrp_idx,]
        
        fit_tauk_ess <- lm(V1 ~ .-V2, data=predgrp)
        fit_tauk_ess_pred <- predict(fit_tauk_ess, newdata=x)
        
        resultss[i, ] <- mregbygroup(data = x, pred_outcome = fit_tauk_ess_pred[-predgrp_idx])
      }
      tauk_ss <-  colMeans(resultss)
      
      # generate tau for 10fold
      flds <- createFolds(x_control_idx, k = 10, list = FALSE, returnTrain = FALSE)
      ## create new dataset copy from tauk prediction
      fold_tau_pred <- yhat
      
      for (i in 1:10){
          fit_tauk_10fold <- lm(V1 ~ .-V2, data=x_control[-which(flds == i),])
          fit_tauk_10fold_pred <- predict(fit_tauk_10fold, newdata=x_control[which(flds == i),])
          #replace control group predicted value with new 10fold leave out predicted value, keep treatment group predicted value unchanged
          fold_tau_pred[x_control_idx][which(flds == i)] <- fit_tauk_10fold_pred
      }
      tauk_10f <-  mregbygroup(data = x, pred_outcome = fold_tau_pred)
      
      # store the results for this k and this n
      est[r,] <- tauk
      estl[r,] <- taukl
      estss[r,] <- tauk_ss
      estf[r,] <- tauk_10f
    }
    # put them into a list
    list_nk <- list(est, estl, estss, estf)
    results <- append(results, list_nk)
  }
}
```

```{r, eval=FALSE}
# we generated 3*3=9 combination of K(num of covariates) and N(number of data)
# each combination has 4 types of estimators, each estimator has 6 results(3 unadjusted, 3 adjusted)
# result has 4*9=36 lists in it
saveRDS(results, file="sim_results_normal/est_normal.Rda")
```

```{r}
results <- readRDS("sim_results_normal/est_normal.Rda")
```

```{r}
library(kableExtra)
bias <- lapply(results, colMeans) %>% unlist() %>% as.vector()
bias_table <- as.data.frame(matrix(bias, nrow=36))

bias_table <- cbind(bias_table[1:12,], bias_table[13:24,], bias_table[25:36,])
colnames(bias_table) <- c(rep(c("Low", "Medium", "High"),6))
rownames(bias_table) <- c("N=200 $\\hat\\tau_k$", "N=200 $\\hat\\tau_k^{LOO}$", 
                          "N=200 $\\hat\\tau_k^{RSS}$","N=200 $\\hat\\tau_k^{10fold}$",
                          "N=1000 $\\hat\\tau_k$", "N=1000 $\\hat\\tau_k^{LOO}$", 
                          "N=1000 $\\hat\\tau_k^{RSS}$","N=1000 $\\hat\\tau_k^{10fold}$",
                          "N=5000 $\\hat\\tau_k$", "N=5000 $\\hat\\tau_k^{LOO}$",
                          "N=5000 $\\hat\\tau_k^{RSS}$","N=5000 $\\hat\\tau_k^{10fold}$")
```

```{r}
kable(bias_table, caption = "Bias in Simulations Using Artificial Data", digits=2,
      format = "html", table.attr = "style='width:100%;'") %>%
add_header_above(c(" ", "Unadjusted" = 3, "Adjusted" = 3, 
                   "Unadjusted" = 3, "Adjusted" = 3, 
                   "Unadjusted" = 3, "Adjusted" = 3)) %>%
add_header_above(c(" ", "K = 10" = 6, "K = 20" = 6, "K = 40" = 6))
```







